<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-09-12 20:28
=======
# Generated by Django 3.1.1 on 2020-09-12 20:16
>>>>>>> dev

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
<<<<<<< HEAD
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='app.federation')),
=======
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='app.federation')),
>>>>>>> dev
            ],
        ),
    ]
