# Generated by Django 3.1.1 on 2020-09-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='team',
            name='photo_url',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='league',
            name='federation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='app.federation'),
        ),
    ]
