# Generated by Django 3.1.1 on 2020-09-14 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_championship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championships', to='app.team'),
        ),
    ]
